"""
Reporter - Generación de reportes de auditoría Bluetooth.
Soporta formatos JSON, HTML y TXT.

Todos los datos dinámicos interpolados en el HTML se escapan con
utils.format.esc(): un dispositivo con un nombre hostil no debe poder
inyectar markup al abrir el reporte en el navegador.
"""

import json
from pathlib import Path

from bluesky import __version__ as _bluesky_version
from bluesky.utils.format import esc


class Reporter:
    """Genera reportes de auditoría en múltiples formatos."""

    def __init__(self, session_data: dict = None):
        self.data = session_data or {}

    def set_data(self, data: dict):
        self.data = data

    def to_json(self, filepath: str = None) -> str:
        """Genera reporte en formato JSON."""
        output = json.dumps(self.data, indent=2, default=str)
        if filepath:
            Path(filepath).write_text(output, encoding="utf-8")
        return output

    def to_txt(self, filepath: str = None) -> str:
        """Genera reporte en formato texto plano."""
        lines = []
        lines.append("=" * 60)
        lines.append("  BLUESKY - BLUETOOTH AUDIT REPORT")
        lines.append("=" * 60)
        lines.append("")

        session = self.data.get("session", {})
        lines.append(f"Session:     {session.get('name', 'N/A')}")
        lines.append(f"Date:        {session.get('date', 'N/A')}")
        lines.append(f"Duration:    {session.get('duration', 'N/A')}")
        lines.append(f"Environment: {session.get('environment', 'N/A')}")
        lines.append("")

        targets = self.data.get("targets", [])
        lines.append(f"[+] Targets Found: {len(targets)}")
        lines.append("-" * 60)

        for i, target in enumerate(targets, 1):
            if not isinstance(target, dict):
                # Targets malformados (p.ej. MACs como strings de un JSON a mano)
                lines.append(f"\n  Target #{i}: {target}")
                continue
            lines.append(f"\n  Target #{i}: {target.get('name', 'Unknown')}")
            lines.append(f"  MAC:        {target.get('mac', 'N/A')}")
            lines.append(f"  RSSI:       {target.get('rssi', 'N/A')} dBm")
            lines.append(f"  First Seen: {target.get('first_seen', 'N/A')}")

            services = target.get("services", [])
            if services:
                lines.append(f"  Services ({len(services)}):")
                for s in services:
                    if isinstance(s, dict):
                        lines.append(f"    - {s.get('name', s.get('uuid', 'Unknown'))}")
                    else:
                        lines.append(f"    - {s}")

            vulns = target.get("vulnerabilities", [])
            if vulns:
                lines.append(f"  Vulnerabilities ({len(vulns)}):")
                for v in vulns:
                    if isinstance(v, dict):
                        lines.append(f"    - {v.get('name', 'Unknown')} ({v.get('severity', 'N/A')})")
                    else:
                        lines.append(f"    - {v}")

        results = self.data.get("results", [])
        if results:
            lines.append(f"\n\n[+] Attack Results: {len(results)}")
            lines.append("-" * 60)
            for r in results:
                if not isinstance(r, dict):
                    lines.append(f"  ⚠️  Resultado malformado: {r!r}")
                    continue
                status = "✅ SUCCESS" if r.get("success") else "❌ FAILED"
                lines.append(f"  {status} | {r.get('module', 'N/A')} -> {r.get('target', 'N/A')}")
                if r.get("error"):
                    lines.append(f"         Error: {r['error']}")

        lines.append("\n" + "=" * 60)
        lines.append(f"  Report generated by bluesky v{_bluesky_version}")
        lines.append("=" * 60)

        output = "\n".join(lines)
        if filepath:
            Path(filepath).write_text(output, encoding="utf-8")
        return output

    def to_html(self, filepath: str = None) -> str:
        """Genera reporte en formato HTML.

        Todos los datos interpolados (nombres de dispositivos, MACs, errores,
        severidades...) se escapan con html.escape: un dispositivo con un
        nombre hostil (p.ej. '<script>...') NO debe ejecutar JS al abrir el
        reporte de auditoría en un navegador.
        """
        session = self.data.get("session", {})
        if not isinstance(session, dict):
            session = {}
        targets = self.data.get("targets", [])
        if not isinstance(targets, list):
            targets = []
        results = self.data.get("results", [])
        if not isinstance(results, list):
            results = []

        # esc() viene de utils/format.py (compartida con Autopilot y futuros
        # generadores de reporte): un único punto de escape HTML.

        def esc_class(value) -> str:
            """Escape para valores usados dentro de un atributo class.

            Whitelist de clases conocidas (severidades + estado del resultado):
            cualquier otro valor se sustituye por 'medium' para no inyectar
            atributos/arbitrario en el HTML.
            """
            allowed = {"critical", "high", "medium", "low", "info",
                       "success", "failed"}
            v = str(value or "medium").strip().lower()
            return v if v in allowed else "medium"

        html = f"""<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>bluesky Audit Report - {esc(session.get('name', 'N/A'))}</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ font-family: 'Segoe UI', Tahoma, sans-serif; background: #0a0e17; color: #e0e0e0; padding: 20px; }}
        .container {{ max-width: 1200px; margin: 0 auto; }}
        .header {{ background: linear-gradient(135deg, #1a237e, #0d47a1); padding: 30px; border-radius: 10px; margin-bottom: 20px; text-align: center; }}
        .header h1 {{ color: #00e5ff; font-size: 2em; }}
        .header h4 {{ color: #90caf9; margin-top: 5px; }}
        .header .badge {{ display: inline-block; background: #00c853; color: #000; padding: 2px 10px; border-radius: 10px; font-size: 0.8em; margin-top: 10px; }}
        .stats {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px; margin-bottom: 20px; }}
        .stat-card {{ background: #111827; border: 1px solid #1e293b; padding: 20px; border-radius: 8px; text-align: center; }}
        .stat-card .number {{ font-size: 2em; font-weight: bold; color: #00e5ff; }}
        .stat-card .label {{ color: #94a3b8; font-size: 0.9em; margin-top: 5px; }}
        .section {{ background: #111827; border: 1px solid #1e293b; border-radius: 8px; padding: 20px; margin-bottom: 20px; }}
        .section h2 {{ color: #00e5ff; border-bottom: 1px solid #1e293b; padding-bottom: 10px; margin-bottom: 15px; }}
        .target {{ background: #0f1729; border: 1px solid #1e293b; border-radius: 6px; padding: 15px; margin-bottom: 10px; }}
        .target h3 {{ color: #38bdf8; }}
        .target .mac {{ color: #94a3b8; font-family: monospace; }}
        .vuln {{ display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 0.8em; margin: 2px; }}
        .vuln.critical {{ background: #dc2626; color: white; }}
        .vuln.high {{ background: #ea580c; color: white; }}
        .vuln.medium {{ background: #ca8a04; color: white; }}
        .vuln.low {{ background: #64748b; color: white; }}
        .result-item {{ padding: 8px 0; border-bottom: 1px solid #1e293b; }}
        .result-item .success {{ color: #4ade80; }}
        .result-item .failed {{ color: #f87171; }}
        table {{ width: 100%; border-collapse: collapse; }}
        th, td {{ padding: 8px 12px; text-align: left; border-bottom: 1px solid #1e293b; }}
        th {{ color: #94a3b8; font-weight: 600; }}
        .footer {{ text-align: center; color: #64748b; padding: 20px; font-size: 0.8em; }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🔵 bluesky Audit Report</h1>
            <h4>{esc(session.get('name', 'N/A'))}</h4>
            <div class="badge">{esc(session.get('date', 'N/A'))}</div>
        </div>

        <div class="stats">
            <div class="stat-card"><div class="number">{len(targets)}</div><div class="label">Targets</div></div>
            <div class="stat-card"><div class="number">{len(results)}</div><div class="label">Tests</div></div>
            <div class="stat-card"><div class="number">{sum(1 for r in results if isinstance(r, dict) and r.get('success'))}</div><div class="label">Successful</div></div>
            <div class="stat-card"><div class="number">{esc(session.get('environment', 'N/A'))}</div><div class="label">Environment</div></div>
        </div>

        <div class="section">
            <h2>📡 Targets Detected</h2>
            {"".join(f'''
            <div class="target">
                <h3>{esc(t.get("name", "Unknown"))}</h3>
                <div class="mac">{esc(t.get("mac", "N/A"))}</div>
                <div>RSSI: {esc(t.get("rssi", "N/A"))} dBm</div>
                <div>First seen: {esc(t.get("first_seen", "N/A"))}</div>
                {f'''<div style="margin-top:5px">{"".join(f'<span class="vuln {esc_class(v.get("severity","medium"))}">{esc(v.get("name",""))}</span>' for v in t.get("vulnerabilities",[]) if isinstance(v, dict))}</div>''' if t.get("vulnerabilities") else ""}
            </div>''' for t in targets if isinstance(t, dict))}
        </div>

        <div class="section">
            <h2>🎯 Attack Results</h2>
            <table>
                <thead><tr><th>Module</th><th>Target</th><th>Status</th><th>Details</th></tr></thead>
                <tbody>
                {"".join(f'''
                <tr>
                    <td>{esc(r.get("module", "N/A"))}</td>
                    <td><code>{esc(r.get("target", "N/A"))}</code></td>
                    <td class="{esc_class('success' if r.get("success") else 'failed')}">{"✅ Success" if r.get("success") else "❌ Failed"}</td>
                    <td>{esc(r.get("error") or (r.get("data", {}).get("message", "") if isinstance(r.get("data"), dict) else ""))}</td>
                </tr>''' for r in results if isinstance(r, dict))}
                </tbody>
            </table>
        </div>

        <div class="footer">
            <p>Generated by bluesky v{_bluesky_version} | Bluetooth Security Auditing Framework</p>
            <p>Documento confidencial de uso exclusivo para auditorías autorizadas</p>
        </div>
    </div>
</body>
</html>"""

        if filepath:
            Path(filepath).write_text(html, encoding="utf-8")
        return html
